apiVersion: v1                                                                                                                                                                                                                                                                                                                                                        
kind: ConfigMap
metadata:
  name: tls-cm
data:
  index.html: |
    <!doctype html>
    <html>
    <head><title>
    <
      <mon site sÃ©curisÃ© ğŸš€</title></head>body>h1>Deploiement du site securisÃ© via https ! ğŸ”</h1>
      <p>servi par kubernetes + nginx ingress</p>
    </body>
    </html>
